spring:
  application:
    name: spring-atomic-syst-acrn-registry
  profiles:
    default: local
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: false
    allow-circular-references: false
  beaninfo:
    ignore: true

logging:
  level:
    root: INFO
